### ISSUE TITLE
Refresh permalinks

### ISSUE THREAD

**Issue by ryanhellyer** [forsitemedia/events-calendar-for-make-benefit-wordpress#1]
The plugin needs to refresh the permalinks on activation, to make the custom post-types work.

**Comment by defries** [comment]
What are the implecations when we do this automagically?

**Comment by ryanhellyer** [comment]
It would make the plugin activation take about an extra 1/1000 s to complete. That's about it I think.

**Comment by ryanhellyer** [comment]
Actually, the original events library used did this already. I had changed something earlier which caused the permalinks to be mucked up. I'm closing this now.

**Comment by ryanhellyer** [comment]
This original events library did have code for doing this, but it was non-functional. It was firing at the wrong point, and it was using an incorrect plugin file location for the activation hook. It is working now.
